openapi: 3.0.1
info:
  title: IP Trust Classifier
  description: Classifies IP addresses using the GreyNoise Community API.
  version: "1.0.0"

servers:
  - url: https://api.greynoise.io

paths:
  /v3/community/{ip}:
    get:
      operationId: IPTrustClassifier
      summary: Classify an IP address using GreyNoise
      description: |
        Looks up an IP address in the GreyNoise Community API to determine its trust level.
      parameters:
        - name: ip
          in: path
          required: true
          schema:
            type: string
          x-ms-openai-param-location: path
      responses:
        '200':
          description: IP classification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ip:
                    type: string
                  classification:
                    type: string
                  name:
                    type: string
                  link:
                    type: string
        '400':
          description: Bad Request (Invalid IP)
        '401':
          description: Unauthorized

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: key

security:
  - ApiKeyAuth: []
