openapi: 3.0.1
info:
  title: IP Trust Classifier
  description: Classifies IP addresses using GreyNoise threat intelligence feed
  version: "1.0.0"

servers:
  - url: https://api.greynoise.io

paths:
  /v3/community/{ip}:
    get:
      operationId: IPTrustClassifier.IPTrustClassifier
      summary: Classify an IP address
      description: Looks up an IP in GreyNoise to determine threat level.
      parameters:
        - name: ip
          in: path
          required: true
          schema:
            type: string
          x-ms-openai-param-location: path
      responses:
        '200':
          description: IP classification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ip:
                    type: string
                  classification:
                    type: string
                    enum: [internal, partner, trusted, suspicious, malicious, unknown]
                  threatScore:
                    type: integer
                  confidence:
                    type: string
        '400':
          description: Invalid IP
        '401':
          description: Unauthorized

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Key

security:
  - ApiKeyAuth: []
